### ISSUE TITLE
lacking content

### ISSUE THREAD

**Issue by cdstelly** [flipxfx/ponway-life#1] opened 2017-08-16 02:10 UTC
plz

**Comment by flipxfx** [comment] 2017-08-16 03:27
unable to reproduce, closing

**Closed by flipxfx** 2017-08-16 03:27 UTC

**Comment by flipxfx** [comment] 2017-08-16 03:29
also check out https://github.com/flipxfx/ponway.life, currently working on exploring a different static site generator in js ;)

**Comment by cdstelly** [comment] 2017-08-16 03:38
because these days you need a js generator for your react bootstrap to get an ajax dom amirite

**Comment by cdstelly** [comment] 2017-08-18 00:45
ummm did you miss a commit to fix [#1](https://github.com/flipxfx/ponway-life/issues/1)?
